# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0036_auto_20160613_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='qiecard',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='qiecard',
            name='temperature',
        ),
        migrations.AddField(
            model_name='attempt',
            name='humidity',
            field=models.FloatField(default=-999.9),
        ),
        migrations.AddField(
            model_name='attempt',
            name='num_failed',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='num_passed',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='temperature',
            field=models.FloatField(default=-999.9),
        ),
    ]
