# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0040_auto_20160615_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 15, 14, 23, 11, 225426, tzinfo=utc), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='card_id',
            field=models.CharField(blank=True, default='NULL', max_length=7, validators=[qie_cards.models.validate_card_id]),
        ),
    ]
