# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0042_auto_20160615_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 15, 14, 52, 41, 24079, tzinfo=datetime.timezone.utc), verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='uid',
            field=models.CharField(default='', max_length=17, unique=True, validators=[qie_cards.models.validate_uid]),
        ),
    ]
