# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0044_auto_20160615_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='card_id',
            field=models.CharField(default='', max_length=7, unique=True, validators=[qie_cards.models.validate_card_id]),
        ),
    ]
