# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0046_auto_20160615_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geo_loc',
            field=models.CharField(default='', max_length=200, verbose_name='Location'),
        ),
    ]
