# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0048_auto_20160617_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='log_file',
            field=models.FileField(default='default.png', upload_to=qie_cards.models.logs_location),
        ),
    ]
