# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0049_auto_20160617_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiecard',
            old_name='card_id',
            new_name='barcode',
        ),
    ]
