# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0050_auto_20160623_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiecard',
            name='major_ver',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='min_ver',
            field=models.CharField(default='', max_length=4),
        ),
    ]
