# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0051_auto_20160624_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiecard',
            old_name='min_ver',
            new_name='minor_ver',
        ),
    ]
