# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0053_qiecard_other_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qiecard',
            name='plane_loc',
        ),
        migrations.AddField(
            model_name='attempt',
            name='plane_loc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
