# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0054_auto_20160627_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=17, validators=[qie_cards.models.validate_uid]),
        ),
    ]
