# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0055_auto_20160630_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='major_ver',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='minor_ver',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='other_ver',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
