# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0057_auto_20160706_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiecard',
            name='igloo_major_ver',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='igloo_minor_ver',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
