# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0058_auto_20160706_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
    ]
