# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0059_auto_20160707_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='hidden_log_file',
            field=models.FileField(default='default.png', upload_to=qie_cards.models.logs_location),
        ),
    ]
