# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0060_attempt_hidden_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='overwrite_pass',
            field=models.BooleanField(default=False),
        ),
    ]
