# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0061_attempt_overwrite_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadoutModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembler', models.CharField(default='', max_length=50, verbose_name='Assembler')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('rm_number', models.IntegerField(default=-1, verbose_name='RM \u2116')),
                ('card_pack_number', models.IntegerField(default=-1, verbose_name='CardPack \u2116')),
                ('mtp_optical_cable', models.CharField(default='', max_length=50, verbose_name='1 MTP to 8 LC optical cable \u2116')),
                ('sipm_control_card', models.IntegerField(default=-1, verbose_name='1 SiPM Control Card with BV mezzanine \u2116')),
                ('sipm_array_1', models.IntegerField(default=-1, verbose_name='SiPM Array S10943-4732 \u2116 (BV1-8)')),
                ('sipm_array_2', models.IntegerField(default=-1, verbose_name='SiPM Array S10943-4732 \u2116 (BV17-24)')),
                ('sipm_array_3', models.IntegerField(default=-1, verbose_name='SiPM Array S10943-4732 \u2116 (BV25-32)')),
                ('sipm_array_4', models.IntegerField(default=-1, verbose_name='SiPM Array S10943-4732 \u2116 (BV33-40)')),
                ('sipm_array_5', models.IntegerField(default=-1, verbose_name='SiPM Array S10943-4732 \u2116 (BV41-48)')),
                ('mixed_sipm_array', models.IntegerField(default=-1, verbose_name='Mixed SiPM array S10943-4733 \u2116 (BV9-16)')),
                ('odu_type', models.CharField(choices=[('1-3', '1-3'), ('2-4', '2-4')], default='', max_length=3, verbose_name='ODU type')),
                ('odu_number', models.IntegerField(default=-1, verbose_name='ODU \u2116')),
                ('minsk', models.IntegerField(default=-1, verbose_name='White box with RM mechanics from Minsk \u2116')),
                ('card_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_1', to='qie_cards.QieCard', verbose_name='QIE card 1 \u2116')),
                ('card_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_2', to='qie_cards.QieCard', verbose_name='QIE card 2 \u2116')),
                ('card_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_3', to='qie_cards.QieCard', verbose_name='QIE card 3 \u2116')),
                ('card_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_4', to='qie_cards.QieCard', verbose_name='QIE card 4 \u2116')),
            ],
        ),
    ]
