# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0063_qieparams_qieshuntparams_qietdcparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='affiliation',
            field=models.CharField(default='', max_length=200, verbose_name='Affiliation'),
        ),
    ]
