# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0066_auto_20160729_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='QieParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=-1)),
                ('qie', models.IntegerField(default=-1)),
                ('cap_ID', models.IntegerField(default=-1)),
                ('cal_range', models.IntegerField(default=-1)),
                ('shunt', models.DecimalField(decimal_places=20, default=float("inf"), max_digits=50)),
                ('slope', models.DecimalField(decimal_places=20, default=float("inf"), max_digits=50)),
                ('offset', models.DecimalField(decimal_places=20, default=float("inf"), max_digits=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date received')),
                ('plots', models.ImageField(default='default.png', upload_to=qie_cards.models.images_location)),
                ('results_file', models.FileField(default='default.png', upload_to=qie_cards.models.logs_location)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.QieCard')),
            ],
        ),
        migrations.CreateModel(
            name='QieTdcParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qie', models.IntegerField(default=-1)),
                ('tdc_start', models.DecimalField(decimal_places=20, default=float("inf"), max_digits=50)),
                ('plots', models.ImageField(default='default.png', upload_to=qie_cards.models.images_location)),
                ('results_file', models.FileField(default='default.png', upload_to=qie_cards.models.logs_location)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.QieCard')),
            ],
        ),
    ]
