# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0070_qieshuntparams_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='qieshuntparams',
            name='group',
            field=models.IntegerField(default=-1),
        ),
    ]
