# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0071_qieshuntparams_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qieshuntparams',
            old_name='results_file',
            new_name='mappings',
        ),
        migrations.RemoveField(
            model_name='qieshuntparams',
            name='plots',
        ),
        migrations.AddField(
            model_name='qieshuntparams',
            name='results',
            field=models.FileField(default='default.png', upload_to=qie_cards.models.logs_location),
        ),
    ]
