# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0072_auto_20160729_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qieshuntparams',
            name='offset',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qieshuntparams',
            name='shunt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qieshuntparams',
            name='slope',
            field=models.CharField(default='', max_length=100),
        ),
    ]
