# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0078_readoutmodule_dcdc_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMBiasVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_01', models.CharField(max_length=50)),
                ('channel_02', models.CharField(max_length=50)),
                ('channel_03', models.CharField(max_length=50)),
                ('channel_04', models.CharField(max_length=50)),
                ('channel_05', models.CharField(max_length=50)),
                ('channel_06', models.CharField(max_length=50)),
                ('channel_07', models.CharField(max_length=50)),
                ('channel_08', models.CharField(max_length=50)),
                ('channel_09', models.CharField(max_length=50)),
                ('channel_10', models.CharField(max_length=50)),
                ('channel_11', models.CharField(max_length=50)),
                ('channel_12', models.CharField(max_length=50)),
                ('channel_13', models.CharField(max_length=50)),
                ('channel_14', models.CharField(max_length=50)),
                ('channel_15', models.CharField(max_length=50)),
                ('channel_16', models.CharField(max_length=50)),
                ('channel_17', models.CharField(max_length=50)),
                ('channel_18', models.CharField(max_length=50)),
                ('channel_19', models.CharField(max_length=50)),
                ('channel_20', models.CharField(max_length=50)),
                ('channel_21', models.CharField(max_length=50)),
                ('channel_22', models.CharField(max_length=50)),
                ('channel_23', models.CharField(max_length=50)),
                ('channel_24', models.CharField(max_length=50)),
                ('channel_25', models.CharField(max_length=50)),
                ('channel_26', models.CharField(max_length=50)),
                ('channel_27', models.CharField(max_length=50)),
                ('channel_28', models.CharField(max_length=50)),
                ('channel_29', models.CharField(max_length=50)),
                ('channel_30', models.CharField(max_length=50)),
                ('channel_31', models.CharField(max_length=50)),
                ('channel_32', models.CharField(max_length=50)),
                ('channel_33', models.CharField(max_length=50)),
                ('channel_34', models.CharField(max_length=50)),
                ('channel_35', models.CharField(max_length=50)),
                ('channel_36', models.CharField(max_length=50)),
                ('channel_37', models.CharField(max_length=50)),
                ('channel_38', models.CharField(max_length=50)),
                ('channel_39', models.CharField(max_length=50)),
                ('channel_40', models.CharField(max_length=50)),
                ('channel_41', models.CharField(max_length=50)),
                ('channel_42', models.CharField(max_length=50)),
                ('channel_43', models.CharField(max_length=50)),
                ('channel_44', models.CharField(max_length=50)),
                ('channel_45', models.CharField(max_length=50)),
                ('channel_46', models.CharField(max_length=50)),
                ('channel_47', models.CharField(max_length=50)),
                ('channel_48', models.CharField(max_length=50)),
            ],
        ),
    ]
