# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0081_auto_20160818_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembler', models.CharField(default='', max_length=50, verbose_name='Assembler')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Assembly')),
                ('place', models.CharField(default='', max_length=50, verbose_name='Location of Assembly')),
                ('cu_number', models.IntegerField(default=-1, verbose_name='CU number')),
                ('pulser_board', models.IntegerField(default=-1, verbose_name='Pulser Board Number')),
                ('optics_box', models.IntegerField(default=-1, verbose_name='Optics Box Number')),
                ('pindiode_led1', models.IntegerField(default=-1, verbose_name='Pindiode_LED1 no.')),
                ('pindiode_led2', models.IntegerField(default=-1, verbose_name='Pindiode_LED2 no.')),
                ('pindiode_laser1', models.IntegerField(default=-1, verbose_name='Pindiode board_laser1 no.')),
                ('pindiode_laser2', models.IntegerField(default=-1, verbose_name='Pindiode board_laser2 no.')),
                ('pindiode_laser3', models.IntegerField(default=-1, verbose_name='Pindiode board_laser3 no.')),
                ('pindiode_laser4', models.IntegerField(default=-1, verbose_name='Pindiode board_laser4 no.')),
                ('qie_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qie_cards.QieCard')),
            ],
        ),
    ]
