# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0082_cu'),
    ]

    operations = [
        migrations.AddField(
            model_name='readoutmodule',
            name='upload',
            field=models.FileField(default='default.png', upload_to='readout_module/'),
        ),
    ]
