# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0084_auto_20160819_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readoutmodule',
            name='upload',
            field=models.FileField(default='default.png', upload_to='readout_module/', verbose_name='Image Upload'),
        ),
    ]
