# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0085_auto_20160819_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cu',
            name='upload',
            field=models.FileField(default='default.png', upload_to='cu_calibration/', verbose_name='Calibration Data'),
        ),
    ]
