# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0086_cu_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cu',
            name='qie_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qie_cards.QieCard', verbose_name='QIE Card'),
        ),
    ]
