# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0087_auto_20160829_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cu',
            name='pindiode_laser1',
            field=models.IntegerField(default=-1, verbose_name='Pindiode board_laser1 '),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_led1',
            field=models.IntegerField(default=-1, verbose_name='Pindiode_LED1 \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_led2',
            field=models.IntegerField(default=-1, verbose_name='Pindiode_LED2 \u2116.'),
        ),
    ]
