# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0088_auto_20160829_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cu',
            name='qc_complete',
            field=models.BooleanField(default=False, verbose_name='QC Complete'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='cu_number',
            field=models.IntegerField(default=-1, verbose_name='CU \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='optics_box',
            field=models.IntegerField(default=-1, verbose_name='Optics Box \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_laser1',
            field=models.IntegerField(default=-1, verbose_name='Pindiode board_laser1 \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_laser2',
            field=models.IntegerField(default=-1, verbose_name='Pindiode board_laser2 \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_laser3',
            field=models.IntegerField(default=-1, verbose_name='Pindiode board_laser3 \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pindiode_laser4',
            field=models.IntegerField(default=-1, verbose_name='Pindiode board_laser4 \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='pulser_board',
            field=models.IntegerField(default=-1, verbose_name='Pulser Board \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='qie_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qie_cards.QieCard', verbose_name='QIE Card \u2116'),
        ),
        migrations.AlterField(
            model_name='cu',
            name='upload',
            field=models.FileField(default='default.png', upload_to='cu_calibration/', verbose_name='QC Data File'),
        ),
    ]
