# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0090_sipmcontrolboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipmControlCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipm_control_card', models.IntegerField(default=-1, verbose_name='SiPM Control Card \u2116')),
                ('bv_converter_card', models.IntegerField(default=-1, verbose_name='BV Converter Card \u2116')),
                ('comments', models.TextField(blank=True, default='', max_length=1000)),
                ('upload', models.FileField(default=False, upload_to=b'', verbose_name='Calibration Data File')),
            ],
        ),
        migrations.DeleteModel(
            name='SipmControlBoard',
        ),
    ]
