# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0091_auto_20160829_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipmcontrolcard',
            name='upload',
            field=models.FileField(default='default.png', upload_to='sipm_control', verbose_name='Calibration Data File'),
        ),
    ]
