# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0093_auto_20160831_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipmcontrolcard',
            name='upload',
            field=models.FileField(default='default.png', upload_to='sipm_control_card', verbose_name='Calibration Data File'),
        ),
    ]
