# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0094_auto_20160831_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationunit',
            name='hirose_signal_connected',
            field=models.BooleanField(default=False, verbose_name='Hirose Signal Connected'),
        ),
        migrations.AddField(
            model_name='calibrationunit',
            name='qie_adapter',
            field=models.IntegerField(default=-1, verbose_name='QIE Adapter \u2116'),
        ),
        migrations.AddField(
            model_name='calibrationunit',
            name='quartz_fiber_inserted',
            field=models.BooleanField(default=False, verbose_name='Quartz Fiber Inserted'),
        ),
        migrations.AddField(
            model_name='calibrationunit',
            name='reference_cable_connected',
            field=models.BooleanField(default=False, verbose_name='Reference Cable Conncected'),
        ),
        migrations.AddField(
            model_name='calibrationunit',
            name='sma_connector_mounted',
            field=models.BooleanField(default=False, verbose_name='SMA Connector Mounted'),
        ),
    ]
