# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0095_auto_20160915_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiecard',
            name='readout_module',
            field=models.IntegerField(default=-1, verbose_name='RM \u2116'),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='readout_module_slot',
            field=models.IntegerField(default=-1, verbose_name='RM \u2116'),
        ),
    ]
