# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0097_readoutmodule_rm_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='readout_module_slot',
            field=models.IntegerField(default=-1, verbose_name='RM Slot'),
        ),
    ]
