# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0098_auto_20160920_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readoutmodule',
            name='rm_uid',
            field=models.CharField(blank=True, default='', max_length=27),
        ),
    ]
