# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0099_auto_20160920_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationunit',
            name='quartz_fiber_inserted',
        ),
        migrations.AddField(
            model_name='calibrationunit',
            name='quartz_fiber_connected',
            field=models.BooleanField(default=False, verbose_name='Quartz Fiber Connected'),
        ),
    ]
