# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0100_auto_20160926_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='readoutmodule',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
