# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0103_sipmcontrolcard_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sipmcontrolcard',
            old_name='results',
            new_name='calibration',
        ),
        migrations.AddField(
            model_name='sipmcontrolcard',
            name='rm_number',
            field=models.IntegerField(default=-1, verbose_name='Readout Module \u2116'),
        ),
    ]
