# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0104_auto_20160930_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipmcontrolcard',
            name='calibration',
        ),
    ]
