# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0105_remove_sipmcontrolcard_calibration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SipmChannel',
        ),
    ]
