# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0106_delete_sipmchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date received')),
                ('geo_loc', models.CharField(default='', max_length=200, verbose_name='Location')),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.ReadoutModule')),
            ],
        ),
    ]
