# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0107_rmlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_01',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_02',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_03',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_04',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_05',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_06',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_07',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_08',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_09',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_11',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_12',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_13',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_14',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_15',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_16',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_17',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_18',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_19',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_20',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_21',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_22',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_23',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_24',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_25',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_26',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_27',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_28',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_29',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_30',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_31',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_32',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_33',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_34',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_35',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_36',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_37',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_38',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_39',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_40',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_41',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_42',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_43',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_44',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_45',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_46',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_47',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmbiasvoltage',
            name='channel_48',
            field=models.CharField(default='', max_length=50),
        ),
    ]
