# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0109_tester_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiecard',
            name='calibration_unit',
            field=models.IntegerField(default=-1, verbose_name='CU \u2116'),
        ),
    ]
