# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0111_culocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationunit',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
